name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main  # or 'master' based on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # specify the required Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      env:
        BUNDLE_PATH: vendor/bundle  # optional, ensures gems are installed locally

    - name: Build the site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production  # optional, sets the environment to production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
