name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change to your branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 2.7  # Specify the Ruby version used for Jekyll

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v1
